/* NUVEL — blog DRAFTS. Written and ready, but NOT imported anywhere yet, so
 * they are tree-shaken out of the build and never appear on the live site.
 * To publish: move an entry into POSTS in blog.ts. Keyword-rich, same voice. */
import type { BlogPost } from "./blog";

export const DRAFTS: BlogPost[] = [
  {
    slug: "web3-fintech-ui-designing-trust",
    title: "Web3 & Fintech UI: Designing Trust into Complex Products",
    excerpt: "Fintech and Web3 products live or die on trust. Here's how thoughtful UI design makes complex flows — wallets, KYC, vesting — feel calm, clear and credible.",
    date: "2026-05-20",
    read: "6 min",
    tags: ["Fintech", "Web3", "Product design"],
    seoTitle: "Web3 & Fintech UI — Designing Trust into Complex Products · Nuvel",
    seoDesc: "Fintech and Web3 UI design that builds trust — how product design makes complex flows like KYC, wallets and vesting clear, calm and credible.",
    body: [
      { p: "In fintech and Web3, design isn't decoration — it's the difference between a product people trust with their money and one they abandon. Complex flows need UI that makes the complicated feel certain." },
      { h: "Clarity over cleverness" },
      { p: "Vesting schedules, KYC steps, wallet connections and on-chain actions are intimidating by default. Good product design breaks them into clear, legible steps with honest status and no hidden surprises." },
      { h: "Trust is a design system" },
      { p: "Consistent components, predictable patterns and calm visual language signal competence. In fintech and Web3 UI, that consistency is what earns the user's confidence to act." },
    ],
  },
  {
    slug: "motion-design-that-converts",
    title: "Motion Design That Converts (Not Just Decorates)",
    excerpt: "Animation can guide attention and lift conversion — or it can just slow your site down. Here's how to use motion design with purpose on a modern website.",
    date: "2026-05-08",
    read: "5 min",
    tags: ["Motion", "UX", "Conversion"],
    seoTitle: "Motion Design That Converts, Not Just Decorates · Nuvel",
    seoDesc: "How to use motion design on a website to guide attention and lift conversion — purposeful animation and interaction design that doesn't slow your site.",
    body: [
      { p: "Motion is one of the most misused tools in web design. Done well, it directs attention and makes a site feel alive. Done badly, it distracts users and tanks performance." },
      { h: "Motion with a job" },
      { p: "Every animation should do something: reveal hierarchy, confirm an action, smooth a transition, or draw the eye to a call to action. Motion for its own sake is just noise that costs load time." },
      { h: "Performance is part of motion" },
      { p: "Great motion design is also fast. Hardware-accelerated, restrained, and respectful of reduced-motion settings — so the experience feels premium on every device without hurting your speed." },
    ],
  },
  {
    slug: "psychology-of-color-in-web-design",
    title: "The Psychology of Color in Web Design",
    excerpt: "Color shapes how visitors feel and act before they read a word. Here's how to use color psychology in web design to build trust and guide conversion.",
    date: "2026-04-24",
    read: "5 min",
    tags: ["Brand", "Web design", "Psychology"],
    seoTitle: "The Psychology of Color in Web Design · Nuvel",
    seoDesc: "How color psychology shapes web design — using color to build brand trust, set mood and guide visitors toward conversion on your website.",
    body: [
      { p: "Before a visitor reads your headline, they've already reacted to your colors. Color sets mood, signals brand personality and quietly steers behaviour — which makes it one of the most powerful tools in web design." },
      { h: "Color as hierarchy" },
      { p: "A disciplined palette uses one accent to mean 'act here'. When every element is colourful, your call to action disappears. Restraint is what makes color work for conversion." },
      { h: "Consistency builds trust" },
      { p: "Color that's used consistently across your website and brand reads as intentional and trustworthy. A documented color system keeps it that way as you grow." },
    ],
  },
  {
    slug: "accessibility-is-a-growth-strategy",
    title: "Accessibility Is a Growth Strategy, Not a Checkbox",
    excerpt: "Accessible web design reaches more customers, ranks better and reduces risk. Here's why accessibility is a growth lever — not a compliance chore.",
    date: "2026-04-10",
    read: "6 min",
    tags: ["Accessibility", "SEO", "Web design"],
    seoTitle: "Accessibility Is a Growth Strategy, Not a Checkbox · Nuvel",
    seoDesc: "Why accessible web design is a growth strategy — reaching more customers, improving SEO and reducing risk with accessibility built into your website.",
    body: [
      { p: "Accessibility gets treated as a legal box to tick. That framing misses the point: an accessible website reaches more people, ranks better and works more reliably for everyone." },
      { h: "More customers, by default" },
      { p: "A large share of users rely on keyboard navigation, screen readers or high contrast. An accessible website simply doesn't lock them out — that's revenue most sites quietly leave on the table." },
      { h: "Accessibility and SEO overlap" },
      { p: "Semantic markup, alt-text, clear structure and good contrast help assistive tech and search engines alike. Build accessibility in from the design stage and you get better SEO for free." },
    ],
  },
  {
    slug: "why-templates-cost-more-than-custom",
    title: "Why Templates Cost More Than Custom in the Long Run",
    excerpt: "A template looks cheaper upfront. Here's why a custom website usually wins on cost, speed and conversion once you count the hidden price of templates.",
    date: "2026-03-27",
    read: "5 min",
    tags: ["Strategy", "Web design", "Cost"],
    seoTitle: "Why Templates Cost More Than Custom in the Long Run · Nuvel",
    seoDesc: "Why a custom website often costs less than a template over time — the hidden costs of template websites in speed, conversion and maintenance.",
    body: [
      { p: "Templates win the first comparison: they're cheap and fast to launch. But the real cost shows up later — in performance, conversion and the hours spent fighting a layout that was never built for your business." },
      { h: "The hidden tax" },
      { p: "Templates carry bloat you don't need, slow your website down, and force your content into someone else's structure. Customising them often costs more than building clean from the start." },
      { h: "Custom is an asset" },
      { p: "A custom website is built around your goals, loads fast, converts better and is yours to own. Over a couple of years, that usually beats the template on total cost — and always on results." },
    ],
  },
  {
    slug: "micro-interactions-small-details-big-impact",
    title: "Micro-interactions: Small Details, Big Impact",
    excerpt: "The tiny moments — a hover, a toggle, a loading state — shape how premium your website feels. Here's how micro-interactions lift UX and brand perception.",
    date: "2026-03-13",
    read: "4 min",
    tags: ["UX", "Motion", "Detail"],
    seoTitle: "Micro-interactions — Small Details, Big Impact · Nuvel",
    seoDesc: "How micro-interactions improve website UX and brand perception — small details like hovers, toggles and states that make a site feel premium.",
    body: [
      { p: "The difference between a website that feels cheap and one that feels premium is rarely the big stuff. It's the micro-interactions — the small, satisfying responses to every action." },
      { h: "Feedback builds confidence" },
      { p: "A button that responds, a form that confirms, a state that animates smoothly — these tiny cues tell users the site is working and worth trusting." },
      { h: "Restraint matters" },
      { p: "Good micro-interactions are felt, not noticed. Subtle, fast and consistent — never a gimmick that gets in the way of the task." },
    ],
  },
  {
    slug: "future-of-work-remote-design-studios-ship-faster",
    title: "The Future of Work: How Remote Design Studios Ship Faster",
    excerpt: "Remote, AI-assisted studios are out-shipping big agencies. Here's how a lean, distributed web design team delivers custom websites faster than ever.",
    date: "2026-02-27",
    read: "5 min",
    tags: ["Future of work", "Studio", "AI"],
    seoTitle: "How Remote Design Studios Ship Faster · Nuvel",
    seoDesc: "How lean, remote, AI-assisted design studios ship custom websites faster than traditional agencies — the future of how web design work gets done.",
    body: [
      { p: "The old model — a big agency, a big team, a big timeline — is being out-run by small, remote studios that ship faster and cost less. The change isn't just where people work; it's how." },
      { h: "Lean beats large" },
      { p: "A tight team where designers and developers work together, with AI handling the busywork, removes the handoffs and meetings that slow agencies down. Fewer people, less drag, faster websites." },
      { h: "Distributed and focused" },
      { p: "Remote-first studios pull talent from anywhere and protect deep-focus time. The result for clients: a custom website designed and built in weeks, not quarters." },
    ],
  },
  {
    slug: "content-first-design",
    title: "Content-First Design: Why Copy Comes Before Layout",
    excerpt: "Designing around real content beats filling a pretty layout with lorem ipsum. Here's why content-first web design produces clearer, higher-converting websites.",
    date: "2026-02-13",
    read: "5 min",
    tags: ["Content", "Web design", "Strategy"],
    seoTitle: "Content-First Design — Why Copy Comes Before Layout · Nuvel",
    seoDesc: "Why content-first web design produces clearer, higher-converting websites — designing around real copy instead of filling layouts with placeholder text.",
    body: [
      { p: "Most websites are designed backwards: a beautiful layout first, real words crammed in later. Content-first design flips that — and the result is a clearer, more convincing website." },
      { h: "Words do the selling" },
      { p: "Your copy is what actually convinces people. Designing around the real message means the layout supports the argument instead of fighting it." },
      { h: "Less rework" },
      { p: "When design starts from real content, you avoid the painful late-stage rebuilds that happen when the words don't fit the boxes. It's faster and it converts better." },
    ],
  },
  {
    slug: "performance-budgets-discipline-behind-fast-sites",
    title: "Performance Budgets: The Discipline Behind Fast Sites",
    excerpt: "Fast websites aren't an accident — they're the result of a performance budget. Here's what a performance budget is and why it should be part of your web design brief.",
    date: "2026-01-30",
    read: "5 min",
    tags: ["Performance", "Web development", "Speed"],
    seoTitle: "Performance Budgets — The Discipline Behind Fast Sites · Nuvel",
    seoDesc: "What a performance budget is and why it makes websites fast — the web design and development discipline behind quick-loading, high-ranking sites.",
    body: [
      { p: "Fast websites don't happen by luck. They happen because someone set a performance budget and held the line — a hard limit on how heavy a page is allowed to be." },
      { h: "A budget forces choices" },
      { p: "When every image, font and script has to fit a weight limit, bloat gets cut early. The discipline is what keeps a site fast as it grows." },
      { h: "Ask for it in the brief" },
      { p: "If speed matters to you — and for SEO and conversion it does — make a performance budget part of your web design brief. A good studio will already work this way." },
    ],
  },
  {
    slug: "brand-identity-in-age-of-ai-generated-everything",
    title: "Brand Identity in the Age of AI-Generated Everything",
    excerpt: "When anyone can generate a logo in seconds, what makes a brand stand out? Here's why distinctive brand identity and design systems matter more, not less, in the AI era.",
    date: "2026-01-16",
    read: "6 min",
    tags: ["Brand", "AI", "Design systems"],
    seoTitle: "Brand Identity in the Age of AI-Generated Everything · Nuvel",
    seoDesc: "Why distinctive brand identity and design systems matter more in the AI era — standing out when anyone can generate a logo and a landing page in seconds.",
    body: [
      { p: "AI can generate a logo, a palette and a landing page in seconds. Which means generic is now free — and distinctiveness is the only thing worth paying for." },
      { h: "A signature idea, not a style" },
      { p: "Strong brand identity starts from one ownable idea, not a trend. That's exactly what AI can't manufacture — and what makes you recognisable in a sea of sameness." },
      { h: "Systems make it stick" },
      { p: "A documented design system turns a good idea into a coherent brand across every touchpoint. In the age of AI-generated everything, consistency and intent are the differentiators." },
    ],
  },
  {
    slug: "dashboards-people-actually-use",
    title: "Dashboards People Actually Use: Data UX Principles",
    excerpt: "Most dashboards drown users in data. Here are the data UX principles behind dashboards and internal tools people actually find useful.",
    date: "2025-12-19",
    read: "6 min",
    tags: ["Product design", "Dashboards", "UX"],
    seoTitle: "Dashboards People Actually Use — Data UX Principles · Nuvel",
    seoDesc: "Data UX principles for dashboards and internal tools — how product design turns overwhelming data into dashboards people actually find useful.",
    body: [
      { p: "A dashboard isn't a place to dump every metric you can measure. It's a tool for making decisions — and most dashboards fail because they forget that." },
      { h: "Answer a question" },
      { p: "Good data UX starts from the question the user is trying to answer, then shows only what helps. Everything else is clutter that hides the signal." },
      { h: "Hierarchy and calm" },
      { p: "Clear hierarchy, restrained color and sensible defaults turn a wall of numbers into something actionable. Calm dashboards get used; noisy ones get ignored." },
    ],
  },
  {
    slug: "death-of-the-homepage-carousel",
    title: "The Death of the Homepage Carousel (and What to Use Instead)",
    excerpt: "Carousels look busy and convert poorly. Here's why the homepage slider is finished — and the web design patterns that actually drive action.",
    date: "2025-12-05",
    read: "4 min",
    tags: ["Web design", "Conversion", "UX"],
    seoTitle: "The Death of the Homepage Carousel · Nuvel",
    seoDesc: "Why homepage carousels convert poorly and what to use instead — web design patterns that drive action better than the classic homepage slider.",
    body: [
      { p: "The homepage carousel feels productive — look how much we can fit! — but the data is damning. People rarely see past the first slide, and the moving content hurts both clarity and speed." },
      { h: "Why it fails" },
      { p: "Carousels split your message, slow your page and ask users to wait for content. Almost everything after slide one goes unseen." },
      { h: "What works instead" },
      { p: "One clear message and one call to action above the fold. If you have several things to say, stack them as scannable sections — not a slideshow nobody finishes." },
    ],
  },
  {
    slug: "cro-2026-data-backed-ways-to-convert",
    title: "CRO 2026: Data-Backed Ways to Convert More Visitors",
    excerpt: "Conversion rate optimisation is part science, part design. Here are the data-backed CRO tactics that turn more of your website traffic into customers in 2026.",
    date: "2025-11-21",
    read: "6 min",
    tags: ["Conversion", "CRO", "Web design"],
    seoTitle: "CRO 2026 — Data-Backed Ways to Convert More Visitors · Nuvel",
    seoDesc: "Data-backed conversion rate optimisation (CRO) tactics for 2026 — web design and UX changes that turn more website visitors into customers.",
    body: [
      { p: "Conversion rate optimisation isn't guesswork or dark patterns. It's the disciplined practice of removing friction and clarifying value — and in 2026 the fundamentals still beat the tricks." },
      { h: "Clarity converts" },
      { p: "The biggest CRO wins are usually clarity wins: a sharper headline, one obvious action, fewer form fields. Confused visitors don't convert." },
      { h: "Speed and trust" },
      { p: "A fast website and visible trust signals quietly lift conversion across the board. Fix those before you obsess over button colors." },
    ],
  },
  {
    slug: "how-to-brief-a-web-design-studio",
    title: "How to Brief a Web Design Studio (and Get Better Results)",
    excerpt: "A great brief gets you a great website. Here's how to brief a web design studio so the project ships fast and hits your real business goals.",
    date: "2025-11-07",
    read: "5 min",
    tags: ["Process", "Web design", "Clients"],
    seoTitle: "How to Brief a Web Design Studio for Better Results · Nuvel",
    seoDesc: "How to brief a web design studio for better results — what to include so your website project ships fast and meets real business goals.",
    body: [
      { p: "The quality of your website often comes down to the quality of your brief. You don't need a fifty-page document — you need clarity on a few things that matter." },
      { h: "Lead with the goal" },
      { p: "What is this website actually for? More leads, more sales, more credibility? One clear goal lets a studio design with intent instead of guessing." },
      { h: "Share the essentials" },
      { p: "Audience, examples you like, brand assets if you have them, and one decision-maker for fast feedback. Give a good studio that, and let them drive the rest." },
    ],
  },
  {
    slug: "performance-first-not-mobile-first",
    title: "Mobile-First Is Old News — Think Performance-First",
    excerpt: "Mobile-first design won. Now the bar has moved. Here's why performance-first is the mindset behind the best modern websites.",
    date: "2025-10-24",
    read: "5 min",
    tags: ["Performance", "Web design", "Mobile"],
    seoTitle: "Mobile-First Is Old News — Think Performance-First · Nuvel",
    seoDesc: "Why performance-first design has replaced mobile-first as the mindset behind the best modern websites — speed as the core web design constraint.",
    body: [
      { p: "Mobile-first design was the right idea for a decade. But everyone designs for mobile now — it's table stakes. The mindset that separates great websites in 2026 is performance-first." },
      { h: "Speed as a constraint" },
      { p: "Performance-first means treating load time as a design decision from the first sketch, not a clean-up task before launch. Every choice is weighed against its cost in speed." },
      { h: "Why it wins" },
      { p: "A performance-first website ranks better, converts better and feels better on every device — mobile included. Speed is the feature that quietly powers all the others." },
    ],
  },
  {
    slug: "hidden-roi-of-good-design-systems",
    title: "The Hidden ROI of Good Design Systems",
    excerpt: "A design system feels like overhead until you measure what it saves. Here's the hidden ROI of design systems — in speed, consistency and cost.",
    date: "2025-10-10",
    read: "5 min",
    tags: ["Design systems", "ROI", "Scale"],
    seoTitle: "The Hidden ROI of Good Design Systems · Nuvel",
    seoDesc: "The hidden ROI of design systems — how scalable design systems and component libraries save time, money and inconsistency as your product grows.",
    body: [
      { p: "Design systems can look like expensive overhead — until you add up what they save. The ROI is real, it's just spread across every future project instead of one invoice." },
      { h: "Speed compounds" },
      { p: "Every new page or feature built from a design system ships faster because the components already exist and already work. That saving compounds with every release." },
      { h: "Consistency is cheaper" },
      { p: "Without a system, inconsistency creeps in and someone pays to fix it later. A design system prevents that drift — keeping your website and product coherent for free." },
    ],
  },
  {
    slug: "ai-research-attention-and-web-design",
    title: "AI Research: What Studies Say About Attention and Web Design",
    excerpt: "Research on attention has clear lessons for web design. Here's what the studies say about how people scan, decide and act on a website — and how to design for it.",
    date: "2025-09-26",
    read: "6 min",
    tags: ["Research", "UX", "Web design"],
    seoTitle: "What Research Says About Attention and Web Design · Nuvel",
    seoDesc: "What attention research means for web design — how studies on scanning, first impressions and decision-making should shape your website's design.",
    body: [
      { p: "Decades of research on human attention point the same direction: people scan, they decide fast, and they act on whatever is clearest. Web design that ignores this fights human nature." },
      { h: "First impressions are instant" },
      { p: "Studies show users judge a website in well under a second. That snap judgement is mostly visual — which is why polished, fast-loading design pays off immediately." },
      { h: "People scan, they don't read" },
      { p: "Eye-tracking research is consistent: visitors scan in patterns, latching onto headings and strong visuals. Design for scanning — clear hierarchy, short blocks, one obvious action — and you work with attention instead of against it." },
    ],
  },
  {
    slug: "multilingual-websites-global-customers",
    title: "Multilingual Websites: Reaching Global Customers Right",
    excerpt: "A multilingual website opens new markets — if it's done properly. Here's how to design and build multilingual websites that rank and convert across languages.",
    date: "2025-09-12",
    read: "6 min",
    tags: ["Multilingual", "SEO", "Web design"],
    seoTitle: "Multilingual Websites — Reaching Global Customers Right · Nuvel",
    seoDesc: "How to design and build multilingual websites that rank and convert — international web design and SEO done right to reach global customers.",
    body: [
      { p: "Adding languages to your website can open whole new markets — but a sloppy translation bolted on at the end does more harm than good. Multilingual done right is a design and SEO decision from the start." },
      { h: "Design for expansion" },
      { p: "Text length changes between languages, layouts shift, and content models need to flex. Multilingual websites should be designed to expand from day one, not retrofitted." },
      { h: "Multilingual SEO" },
      { p: "Proper language tagging, localised content and clean structure let search engines serve the right version to the right market — turning a multilingual website into real international reach." },
    ],
  },
  {
    slug: "typography-on-the-web-fonts-that-convert",
    title: "Typography on the Web: Choosing Fonts That Convert",
    excerpt: "Type sets the tone and carries the message. Here's how to choose web typography that's fast, readable and on-brand — and quietly lifts conversion.",
    date: "2025-08-29",
    read: "5 min",
    tags: ["Typography", "Web design", "Brand"],
    seoTitle: "Typography on the Web — Choosing Fonts That Convert · Nuvel",
    seoDesc: "How to choose web typography that's fast, readable and on-brand — web design type choices that improve readability and quietly lift conversion.",
    body: [
      { p: "Typography is most of what a visitor reads, yet it's often an afterthought. The right type makes a website feel credible and effortless; the wrong type quietly undermines everything else." },
      { h: "Readable beats fancy" },
      { p: "On the web, clarity wins. Generous size, comfortable line length and strong contrast do more for engagement than any decorative font ever will." },
      { h: "Type is performance too" },
      { p: "Every font weight has a cost. Choosing and loading type carefully keeps your website fast — so good typography supports both brand and speed at once." },
    ],
  },
];
