/* NUVEL — blog posts (published). Keyword-rich articles aimed at clients
 * searching for web design, fast websites, AI-assisted design and modern
 * product/brand work. Drafts live in blog-drafts.ts until they go live. */

export interface BlogBlock {
  h?: string;
  p?: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string; // ISO
  read: string;
  tags: string[];
  seoTitle: string;
  seoDesc: string;
  body: BlogBlock[];
}

export const POSTS: BlogPost[] = [
  {
    slug: "typography-on-the-web-fonts-that-convert",
    title: "Typography on the Web: Choosing Fonts That Convert",
    excerpt: "Type sets the tone and carries the message. Here's how to choose web typography that's fast, readable and on-brand — and quietly lifts conversion.",
    date: "2026-09-28",
    read: "5 min",
    tags: ["Typography", "Web design", "Brand"],
    seoTitle: "Typography on the Web — Choosing Fonts That Convert · Nuvel",
    seoDesc: "How to choose web typography that's fast, readable and on-brand — web design type choices that improve readability and quietly lift conversion.",
    body: [
      { p: "Typography is most of what a visitor reads, yet it's often an afterthought. The right type makes a website feel credible and effortless; the wrong type quietly undermines everything else." },
      { h: "Readable beats fancy" },
      { p: "On the web, clarity wins. Generous size, comfortable line length and strong contrast do more for engagement than any decorative font ever will." },
      { h: "Type is performance too" },
      { p: "Every font weight has a cost. Choosing and loading type carefully keeps your website fast — so good typography supports both brand and speed at once." },
    ],
  },
  {
    slug: "multilingual-websites-global-customers",
    title: "Multilingual Websites: Reaching Global Customers Right",
    excerpt: "A multilingual website opens new markets — if it's done properly. Here's how to design and build multilingual websites that rank and convert across languages.",
    date: "2026-09-21",
    read: "6 min",
    tags: ["Multilingual", "SEO", "Web design"],
    seoTitle: "Multilingual Websites — Reaching Global Customers Right · Nuvel",
    seoDesc: "How to design and build multilingual websites that rank and convert — international web design and SEO done right to reach global customers.",
    body: [
      { p: "Adding languages to your website can open whole new markets — but a sloppy translation bolted on at the end does more harm than good. Multilingual done right is a design and SEO decision from the start." },
      { h: "Design for expansion" },
      { p: "Text length changes between languages, layouts shift, and content models need to flex. Multilingual websites should be designed to expand from day one, not retrofitted." },
      { h: "Multilingual SEO" },
      { p: "Proper language tagging, localised content and clean structure let search engines serve the right version to the right market — turning a multilingual website into real international reach." },
    ],
  },
  {
    slug: "ai-research-attention-and-web-design",
    title: "AI Research: What Studies Say About Attention and Web Design",
    excerpt: "Research on attention has clear lessons for web design. Here's what the studies say about how people scan, decide and act on a website — and how to design for it.",
    date: "2026-09-14",
    read: "6 min",
    tags: ["Research", "UX", "Web design"],
    seoTitle: "What Research Says About Attention and Web Design · Nuvel",
    seoDesc: "What attention research means for web design — how studies on scanning, first impressions and decision-making should shape your website's design.",
    body: [
      { p: "Decades of research on human attention point the same direction: people scan, they decide fast, and they act on whatever is clearest. Web design that ignores this fights human nature." },
      { h: "First impressions are instant" },
      { p: "Studies show users judge a website in well under a second. That snap judgement is mostly visual — which is why polished, fast-loading design pays off immediately." },
      { h: "People scan, they don't read" },
      { p: "Eye-tracking research is consistent: visitors scan in patterns, latching onto headings and strong visuals. Design for scanning — clear hierarchy, short blocks, one obvious action — and you work with attention instead of against it." },
    ],
  },
  {
    slug: "hidden-roi-of-good-design-systems",
    title: "The Hidden ROI of Good Design Systems",
    excerpt: "A design system feels like overhead until you measure what it saves. Here's the hidden ROI of design systems — in speed, consistency and cost.",
    date: "2026-09-07",
    read: "5 min",
    tags: ["Design systems", "ROI", "Scale"],
    seoTitle: "The Hidden ROI of Good Design Systems · Nuvel",
    seoDesc: "The hidden ROI of design systems — how scalable design systems and component libraries save time, money and inconsistency as your product grows.",
    body: [
      { p: "Design systems can look like expensive overhead — until you add up what they save. The ROI is real, it's just spread across every future project instead of one invoice." },
      { h: "Speed compounds" },
      { p: "Every new page or feature built from a design system ships faster because the components already exist and already work. That saving compounds with every release." },
      { h: "Consistency is cheaper" },
      { p: "Without a system, inconsistency creeps in and someone pays to fix it later. A design system prevents that drift — keeping your website and product coherent for free." },
    ],
  },
  {
    slug: "performance-first-not-mobile-first",
    title: "Mobile-First Is Old News — Think Performance-First",
    excerpt: "Mobile-first design won. Now the bar has moved. Here's why performance-first is the mindset behind the best modern websites.",
    date: "2026-08-31",
    read: "5 min",
    tags: ["Performance", "Web design", "Mobile"],
    seoTitle: "Mobile-First Is Old News — Think Performance-First · Nuvel",
    seoDesc: "Why performance-first design has replaced mobile-first as the mindset behind the best modern websites — speed as the core web design constraint.",
    body: [
      { p: "Mobile-first design was the right idea for a decade. But everyone designs for mobile now — it's table stakes. The mindset that separates great websites in 2026 is performance-first." },
      { h: "Speed as a constraint" },
      { p: "Performance-first means treating load time as a design decision from the first sketch, not a clean-up task before launch. Every choice is weighed against its cost in speed." },
      { h: "Why it wins" },
      { p: "A performance-first website ranks better, converts better and feels better on every device — mobile included. Speed is the feature that quietly powers all the others." },
    ],
  },
  {
    slug: "how-to-brief-a-web-design-studio",
    title: "How to Brief a Web Design Studio (and Get Better Results)",
    excerpt: "A great brief gets you a great website. Here's how to brief a web design studio so the project ships fast and hits your real business goals.",
    date: "2026-08-24",
    read: "5 min",
    tags: ["Process", "Web design", "Clients"],
    seoTitle: "How to Brief a Web Design Studio for Better Results · Nuvel",
    seoDesc: "How to brief a web design studio for better results — what to include so your website project ships fast and meets real business goals.",
    body: [
      { p: "The quality of your website often comes down to the quality of your brief. You don't need a fifty-page document — you need clarity on a few things that matter." },
      { h: "Lead with the goal" },
      { p: "What is this website actually for? More leads, more sales, more credibility? One clear goal lets a studio design with intent instead of guessing." },
      { h: "Share the essentials" },
      { p: "Audience, examples you like, brand assets if you have them, and one decision-maker for fast feedback. Give a good studio that, and let them drive the rest." },
    ],
  },
  {
    slug: "cro-2026-data-backed-ways-to-convert",
    title: "CRO 2026: Data-Backed Ways to Convert More Visitors",
    excerpt: "Conversion rate optimisation is part science, part design. Here are the data-backed CRO tactics that turn more of your website traffic into customers in 2026.",
    date: "2026-08-17",
    read: "6 min",
    tags: ["Conversion", "CRO", "Web design"],
    seoTitle: "CRO 2026 — Data-Backed Ways to Convert More Visitors · Nuvel",
    seoDesc: "Data-backed conversion rate optimisation (CRO) tactics for 2026 — web design and UX changes that turn more website visitors into customers.",
    body: [
      { p: "Conversion rate optimisation isn't guesswork or dark patterns. It's the disciplined practice of removing friction and clarifying value — and in 2026 the fundamentals still beat the tricks." },
      { h: "Clarity converts" },
      { p: "The biggest CRO wins are usually clarity wins: a sharper headline, one obvious action, fewer form fields. Confused visitors don't convert." },
      { h: "Speed and trust" },
      { p: "A fast website and visible trust signals quietly lift conversion across the board. Fix those before you obsess over button colors." },
    ],
  },
  {
    slug: "death-of-the-homepage-carousel",
    title: "The Death of the Homepage Carousel (and What to Use Instead)",
    excerpt: "Carousels look busy and convert poorly. Here's why the homepage slider is finished — and the web design patterns that actually drive action.",
    date: "2026-08-10",
    read: "4 min",
    tags: ["Web design", "Conversion", "UX"],
    seoTitle: "The Death of the Homepage Carousel · Nuvel",
    seoDesc: "Why homepage carousels convert poorly and what to use instead — web design patterns that drive action better than the classic homepage slider.",
    body: [
      { p: "The homepage carousel feels productive — look how much we can fit! — but the data is damning. People rarely see past the first slide, and the moving content hurts both clarity and speed." },
      { h: "Why it fails" },
      { p: "Carousels split your message, slow your page and ask users to wait for content. Almost everything after slide one goes unseen." },
      { h: "What works instead" },
      { p: "One clear message and one call to action above the fold. If you have several things to say, stack them as scannable sections — not a slideshow nobody finishes." },
    ],
  },
  {
    slug: "dashboards-people-actually-use",
    title: "Dashboards People Actually Use: Data UX Principles",
    excerpt: "Most dashboards drown users in data. Here are the data UX principles behind dashboards and internal tools people actually find useful.",
    date: "2026-08-03",
    read: "6 min",
    tags: ["Product design", "Dashboards", "UX"],
    seoTitle: "Dashboards People Actually Use — Data UX Principles · Nuvel",
    seoDesc: "Data UX principles for dashboards and internal tools — how product design turns overwhelming data into dashboards people actually find useful.",
    body: [
      { p: "A dashboard isn't a place to dump every metric you can measure. It's a tool for making decisions — and most dashboards fail because they forget that." },
      { h: "Answer a question" },
      { p: "Good data UX starts from the question the user is trying to answer, then shows only what helps. Everything else is clutter that hides the signal." },
      { h: "Hierarchy and calm" },
      { p: "Clear hierarchy, restrained color and sensible defaults turn a wall of numbers into something actionable. Calm dashboards get used; noisy ones get ignored." },
    ],
  },
  {
    slug: "brand-identity-in-age-of-ai-generated-everything",
    title: "Brand Identity in the Age of AI-Generated Everything",
    excerpt: "When anyone can generate a logo in seconds, what makes a brand stand out? Here's why distinctive brand identity and design systems matter more, not less, in the AI era.",
    date: "2026-07-27",
    read: "6 min",
    tags: ["Brand", "AI", "Design systems"],
    seoTitle: "Brand Identity in the Age of AI-Generated Everything · Nuvel",
    seoDesc: "Why distinctive brand identity and design systems matter more in the AI era — standing out when anyone can generate a logo and a landing page in seconds.",
    body: [
      { p: "AI can generate a logo, a palette and a landing page in seconds. Which means generic is now free — and distinctiveness is the only thing worth paying for." },
      { h: "A signature idea, not a style" },
      { p: "Strong brand identity starts from one ownable idea, not a trend. That's exactly what AI can't manufacture — and what makes you recognisable in a sea of sameness." },
      { h: "Systems make it stick" },
      { p: "A documented design system turns a good idea into a coherent brand across every touchpoint. In the age of AI-generated everything, consistency and intent are the differentiators." },
    ],
  },
  {
    slug: "performance-budgets-discipline-behind-fast-sites",
    title: "Performance Budgets: The Discipline Behind Fast Sites",
    excerpt: "Fast websites aren't an accident — they're the result of a performance budget. Here's what a performance budget is and why it should be part of your web design brief.",
    date: "2026-07-20",
    read: "5 min",
    tags: ["Performance", "Web development", "Speed"],
    seoTitle: "Performance Budgets — The Discipline Behind Fast Sites · Nuvel",
    seoDesc: "What a performance budget is and why it makes websites fast — the web design and development discipline behind quick-loading, high-ranking sites.",
    body: [
      { p: "Fast websites don't happen by luck. They happen because someone set a performance budget and held the line — a hard limit on how heavy a page is allowed to be." },
      { h: "A budget forces choices" },
      { p: "When every image, font and script has to fit a weight limit, bloat gets cut early. The discipline is what keeps a site fast as it grows." },
      { h: "Ask for it in the brief" },
      { p: "If speed matters to you — and for SEO and conversion it does — make a performance budget part of your web design brief. A good studio will already work this way." },
    ],
  },
  {
    slug: "content-first-design",
    title: "Content-First Design: Why Copy Comes Before Layout",
    excerpt: "Designing around real content beats filling a pretty layout with lorem ipsum. Here's why content-first web design produces clearer, higher-converting websites.",
    date: "2026-07-13",
    read: "5 min",
    tags: ["Content", "Web design", "Strategy"],
    seoTitle: "Content-First Design — Why Copy Comes Before Layout · Nuvel",
    seoDesc: "Why content-first web design produces clearer, higher-converting websites — designing around real copy instead of filling layouts with placeholder text.",
    body: [
      { p: "Most websites are designed backwards: a beautiful layout first, real words crammed in later. Content-first design flips that — and the result is a clearer, more convincing website." },
      { h: "Words do the selling" },
      { p: "Your copy is what actually convinces people. Designing around the real message means the layout supports the argument instead of fighting it." },
      { h: "Less rework" },
      { p: "When design starts from real content, you avoid the painful late-stage rebuilds that happen when the words don't fit the boxes. It's faster and it converts better." },
    ],
  },
  {
    slug: "future-of-work-remote-design-studios-ship-faster",
    title: "The Future of Work: How Remote Design Studios Ship Faster",
    excerpt: "Remote, AI-assisted studios are out-shipping big agencies. Here's how a lean, distributed web design team delivers custom websites faster than ever.",
    date: "2026-07-06",
    read: "5 min",
    tags: ["Future of work", "Studio", "AI"],
    seoTitle: "How Remote Design Studios Ship Faster · Nuvel",
    seoDesc: "How lean, remote, AI-assisted design studios ship custom websites faster than traditional agencies — the future of how web design work gets done.",
    body: [
      { p: "The old model — a big agency, a big team, a big timeline — is being out-run by small, remote studios that ship faster and cost less. The change isn't just where people work; it's how." },
      { h: "Lean beats large" },
      { p: "A tight team where designers and developers work together, with AI handling the busywork, removes the handoffs and meetings that slow agencies down. Fewer people, less drag, faster websites." },
      { h: "Distributed and focused" },
      { p: "Remote-first studios pull talent from anywhere and protect deep-focus time. The result for clients: a custom website designed and built in weeks, not quarters." },
    ],
  },
  {
    slug: "micro-interactions-small-details-big-impact",
    title: "Micro-interactions: Small Details, Big Impact",
    excerpt: "The tiny moments — a hover, a toggle, a loading state — shape how premium your website feels. Here's how micro-interactions lift UX and brand perception.",
    date: "2026-06-29",
    read: "4 min",
    tags: ["UX", "Motion", "Detail"],
    seoTitle: "Micro-interactions — Small Details, Big Impact · Nuvel",
    seoDesc: "How micro-interactions improve website UX and brand perception — small details like hovers, toggles and states that make a site feel premium.",
    body: [
      { p: "The difference between a website that feels cheap and one that feels premium is rarely the big stuff. It's the micro-interactions — the small, satisfying responses to every action." },
      { h: "Feedback builds confidence" },
      { p: "A button that responds, a form that confirms, a state that animates smoothly — these tiny cues tell users the site is working and worth trusting." },
      { h: "Restraint matters" },
      { p: "Good micro-interactions are felt, not noticed. Subtle, fast and consistent — never a gimmick that gets in the way of the task." },
    ],
  },
  {
    slug: "why-templates-cost-more-than-custom",
    title: "Why Templates Cost More Than Custom in the Long Run",
    excerpt: "A template looks cheaper upfront. Here's why a custom website usually wins on cost, speed and conversion once you count the hidden price of templates.",
    date: "2026-06-22",
    read: "5 min",
    tags: ["Strategy", "Web design", "Cost"],
    seoTitle: "Why Templates Cost More Than Custom in the Long Run · Nuvel",
    seoDesc: "Why a custom website often costs less than a template over time — the hidden costs of template websites in speed, conversion and maintenance.",
    body: [
      { p: "Templates win the first comparison: they're cheap and fast to launch. But the real cost shows up later — in performance, conversion and the hours spent fighting a layout that was never built for your business." },
      { h: "The hidden tax" },
      { p: "Templates carry bloat you don't need, slow your website down, and force your content into someone else's structure. Customising them often costs more than building clean from the start." },
      { h: "Custom is an asset" },
      { p: "A custom website is built around your goals, loads fast, converts better and is yours to own. Over a couple of years, that usually beats the template on total cost — and always on results." },
    ],
  },
  {
    slug: "accessibility-is-a-growth-strategy",
    title: "Accessibility Is a Growth Strategy, Not a Checkbox",
    excerpt: "Accessible web design reaches more customers, ranks better and reduces risk. Here's why accessibility is a growth lever — not a compliance chore.",
    date: "2026-06-15",
    read: "6 min",
    tags: ["Accessibility", "SEO", "Web design"],
    seoTitle: "Accessibility Is a Growth Strategy, Not a Checkbox · Nuvel",
    seoDesc: "Why accessible web design is a growth strategy — reaching more customers, improving SEO and reducing risk with accessibility built into your website.",
    body: [
      { p: "Accessibility gets treated as a legal box to tick. That framing misses the point: an accessible website reaches more people, ranks better and works more reliably for everyone." },
      { h: "More customers, by default" },
      { p: "A large share of users rely on keyboard navigation, screen readers or high contrast. An accessible website simply doesn't lock them out — that's revenue most sites quietly leave on the table." },
      { h: "Accessibility and SEO overlap" },
      { p: "Semantic markup, alt-text, clear structure and good contrast help assistive tech and search engines alike. Build accessibility in from the design stage and you get better SEO for free." },
    ],
  },
  {
    slug: "psychology-of-color-in-web-design",
    title: "The Psychology of Color in Web Design",
    excerpt: "Color shapes how visitors feel and act before they read a word. Here's how to use color psychology in web design to build trust and guide conversion.",
    date: "2026-06-12",
    read: "5 min",
    tags: ["Brand", "Web design", "Psychology"],
    seoTitle: "The Psychology of Color in Web Design · Nuvel",
    seoDesc: "How color psychology shapes web design — using color to build brand trust, set mood and guide visitors toward conversion on your website.",
    body: [
      { p: "Before a visitor reads your headline, they've already reacted to your colors. Color sets mood, signals brand personality and quietly steers behaviour — which makes it one of the most powerful tools in web design." },
      { h: "Color as hierarchy" },
      { p: "A disciplined palette uses one accent to mean 'act here'. When every element is colourful, your call to action disappears. Restraint is what makes color work for conversion." },
      { h: "Consistency builds trust" },
      { p: "Color that's used consistently across your website and brand reads as intentional and trustworthy. A documented color system keeps it that way as you grow." },
    ],
  },
  {
    slug: "motion-design-that-converts",
    title: "Motion Design That Converts (Not Just Decorates)",
    excerpt: "Animation can guide attention and lift conversion — or it can just slow your site down. Here's how to use motion design with purpose on a modern website.",
    date: "2026-06-11",
    read: "5 min",
    tags: ["Motion", "UX", "Conversion"],
    seoTitle: "Motion Design That Converts, Not Just Decorates · Nuvel",
    seoDesc: "How to use motion design on a website to guide attention and lift conversion — purposeful animation and interaction design that doesn't slow your site.",
    body: [
      { p: "Motion is one of the most misused tools in web design. Done well, it directs attention and makes a site feel alive. Done badly, it distracts users and tanks performance." },
      { h: "Motion with a job" },
      { p: "Every animation should do something: reveal hierarchy, confirm an action, smooth a transition, or draw the eye to a call to action. Motion for its own sake is just noise that costs load time." },
      { h: "Performance is part of motion" },
      { p: "Great motion design is also fast. Hardware-accelerated, restrained, and respectful of reduced-motion settings — so the experience feels premium on every device without hurting your speed." },
    ],
  },
  {
    slug: "web3-fintech-ui-designing-trust",
    title: "Web3 & Fintech UI: Designing Trust into Complex Products",
    excerpt: "Fintech and Web3 products live or die on trust. Here's how thoughtful UI design makes complex flows — wallets, KYC, vesting — feel calm, clear and credible.",
    date: "2026-06-09",
    read: "6 min",
    tags: ["Fintech", "Web3", "Product design"],
    seoTitle: "Web3 & Fintech UI — Designing Trust into Complex Products · Nuvel",
    seoDesc: "Fintech and Web3 UI design that builds trust — how product design makes complex flows like KYC, wallets and vesting clear, calm and credible.",
    body: [
      { p: "In fintech and Web3, design isn't decoration — it's the difference between a product people trust with their money and one they abandon. Complex flows need UI that makes the complicated feel certain." },
      { h: "Clarity over cleverness" },
      { p: "Vesting schedules, KYC steps, wallet connections and on-chain actions are intimidating by default. Good product design breaks them into clear, legible steps with honest status and no hidden surprises." },
      { h: "Trust is a design system" },
      { p: "Consistent components, predictable patterns and calm visual language signal competence. In fintech and Web3 UI, that consistency is what earns the user's confidence to act." },
    ],
  },
  {
    slug: "ai-tools-cut-web-development-time-in-half",
    title: "How AI Tools Cut Web Development Time in Half",
    excerpt: "AI coding and design tools are compressing build timelines dramatically. Here's where the time actually goes — and how a fast web design studio turns that into two-week launches.",
    date: "2026-06-02",
    read: "5 min",
    tags: ["AI", "Web development", "Speed"],
    seoTitle: "How AI Tools Cut Web Development Time in Half · Nuvel",
    seoDesc: "How AI tools cut web development and design time in half — and how a modern web design studio uses them to ship custom websites in two weeks.",
    body: [
      { p: "The promise of AI in web development isn't that it writes your whole site. It's that it removes the slow, repetitive layers — so a custom website that used to take a month now ships in two weeks." },
      { h: "Where the hours used to go" },
      { p: "Scaffolding components, wiring forms, writing tests, generating content variants, optimising images, handling translations. None of it required deep creativity — but all of it ate time. AI now does the first 80% of these tasks in minutes." },
      { h: "What the saved time buys" },
      { p: "Better strategy, sharper art direction, more iteration on the things that convert. For clients, faster web development means a fast website live sooner — and a team focused on outcomes, not busywork." },
    ],
  },
  {
    slug: "ai-automating-web-design-workflows",
    title: "How AI Is Automating Web Design Workflows (and What It Means for Your Next Website)",
    excerpt:
      "AI is quietly rewriting how websites get designed and built. Here's where it actually saves time — and why a fast, AI-assisted web design studio can ship your site in weeks, not months.",
    date: "2026-05-28",
    read: "6 min",
    tags: ["AI", "Web design", "Workflow"],
    seoTitle: "How AI Is Automating Web Design Workflows · Nuvel",
    seoDesc:
      "How AI automates web design and development workflows — and what it means for businesses that want a fast, custom website designed and built in weeks.",
    body: [
      { p: "For most of the last decade, building a custom website meant months of discovery decks, static mockups and slow back-and-forth. AI is collapsing that timeline. At a modern web design studio, AI now handles the repetitive layers of the work — so designers and developers spend their time on the things that actually move the needle: strategy, art direction and conversion." },
      { h: "Where AI actually saves time" },
      { p: "The biggest wins aren't flashy. AI accelerates content drafting, image cleanup, code scaffolding, copy variations, alt-text and translation. A task that used to eat a full day — say, generating a tested component or a multilingual content pass — now takes an hour. Multiply that across a project and a two-week website build stops sounding ambitious and starts sounding normal." },
      { h: "What it doesn't replace" },
      { p: "AI doesn't have taste, and it doesn't understand your customer. The signature idea behind a brand, the one screen that has to convert, the judgement call on what to cut — that's still human work. The best results come from a tight team using AI as an accelerator, not an autopilot." },
      { h: "What it means for your next website" },
      { p: "If you're commissioning a website in 2026, you should expect speed without a quality discount. AI-assisted web design and development means you see real, working screens in days, ship in weeks, and pay for outcomes rather than hours. Ask any studio you're evaluating how they use AI in their workflow — the answer tells you a lot about how fast and how modern they really are." },
      { p: "At Nuvel, AI is baked into how we design and build — which is exactly why we can ship whole websites and platforms in one to two weeks without cutting corners." },
    ],
  },
  {
    slug: "why-fast-websites-win",
    title: "Why Fast Websites Win: The Two-Week Build, Explained",
    excerpt:
      "Speed isn't a discount on quality — it's a competitive advantage. Here's how a focused web design process ships a custom website in two weeks, and why that matters for your business.",
    date: "2026-05-14",
    read: "5 min",
    tags: ["Process", "Fast websites", "Strategy"],
    seoTitle: "Why Fast Websites Win — The Two-Week Build · Nuvel",
    seoDesc:
      "Why a fast, two-week website build beats a six-month project — the web design process behind shipping a custom website quickly without sacrificing quality.",
    body: [
      { p: "Long projects don't fail because of bad design. They fail because momentum dies. Scope creeps, stakeholders rotate, the market shifts, and the site that launches eight months later answers a question nobody's asking anymore. A fast website build sidesteps all of that." },
      { h: "Speed forces clarity" },
      { p: "When you commit to shipping a website in two weeks, you're forced to decide what actually matters. One clear goal. One audience. One thing the site must do. That constraint is a feature, not a bug — it kills the bloat that slows most web design projects to a crawl." },
      { h: "How the two-week build works" },
      { p: "It comes down to a tight rhythm: a focused kickoff, art direction and key screens in the first few days, then design and front-end build moving together on a tested system. Daily previews mean no big-reveal surprises. By the end, you have a fast-loading, SEO-ready website you can run yourself." },
      { h: "Fast and good, not fast or good" },
      { p: "The trade-off people fear — speed versus quality — is mostly a myth created by slow processes. Performance budgets, accessibility and clean code are non-negotiable regardless of timeline. A fast website that ranks, loads and converts is simply the result of an opinionated team that has removed the waste." },
    ],
  },
  {
    slug: "real-cost-of-a-slow-website",
    title: "The Real Cost of a Slow Website (and How to Fix It)",
    excerpt:
      "A slow website quietly bleeds revenue, rankings and trust. Here's what page speed really costs you — and the web design and development fixes that have the biggest impact.",
    date: "2026-04-30",
    read: "6 min",
    tags: ["Performance", "SEO", "Conversion"],
    seoTitle: "The Real Cost of a Slow Website — and How to Fix It · Nuvel",
    seoDesc:
      "What a slow website really costs in conversions and SEO rankings — plus the web design and performance fixes that load your site faster and convert more.",
    body: [
      { p: "Most businesses underestimate what a slow website costs them. It's invisible: there's no invoice for the customers who bounced before the page loaded. But the data is brutal — every extra second of load time drags down conversion, search ranking and brand trust simultaneously." },
      { h: "The numbers: what a one-second delay actually costs" },
      { p: "Portent's research puts the conversion rate of a page loading in one second at 39% — by five seconds, it's 22%. That's not a rounding error; it's nearly half your potential customers gone before they decide. For a business generating £200k in annual revenue from their website, a two-second speed improvement could recover tens of thousands in sales that were silently leaking away." },
      { h: "What Google actually measures: Core Web Vitals explained" },
      { p: "Google uses three specific signals as ranking factors. Largest Contentful Paint (LCP) measures when the main content appears — good is under 2.5 seconds. Cumulative Layout Shift (CLS) measures whether elements jump around while loading — good is under 0.1. Interaction to Next Paint (INP) measures how quickly the page responds to clicks and taps — good is under 200 milliseconds. Check your scores for free at PageSpeed Insights. Most small business sites built on WordPress with lots of plugins fail at least two of these." },
      { h: "The compounding cost" },
      { p: "Search engines treat speed as a ranking signal, so a slow site is harder to find. Once found, slow pages convert worse — visitors abandon carts and contact forms before they submit. And the people who do stay quietly downgrade their impression of your brand. Slow reads as careless, even when your product is excellent. Each of these effects compounds the others: lower rankings mean less traffic, lower conversion means less revenue from the traffic you have." },
      { h: "The hidden costs beyond conversion" },
      { p: "Slow sites cost you in ways that won't appear in your analytics. Every second of load time increases bounce rate — Google records this as a signal that your page wasn't useful, which feeds back into lower rankings over time. Slower pages get crawled less frequently, meaning new content takes longer to get indexed. On mobile (which is now the majority of web traffic), a slow page doesn't just annoy users — it can actively exhaust their data on metered connections, making your site hostile to a significant portion of your audience." },
      { h: "Why most slow websites stay slow" },
      { p: "The most common reason slow sites don't get fixed is that the speed problems are architectural, not cosmetic. Page builders like Elementor or Divi generate bloated HTML and load enormous CSS and JavaScript bundles that can't be optimised away after the fact. No caching plugin can fully compensate for a fundamentally overweight codebase. Understanding whether you're dealing with a fixable performance issue or a structural one determines whether you should patch or rebuild." },
      { h: "The fixes that actually matter" },
      { p: "Most speed problems come down to a handful of culprits: oversized images, render-blocking scripts, bloated page builders and no performance budget. The high-impact fixes are: compressing every image to WebP format and lazy-loading below-the-fold images; deferring or removing third-party scripts like chat widgets and marketing pixels; and choosing a host that includes a CDN. A good web design and development team treats performance as a design constraint from day one, not an afterthought." },
      { h: "Quick wins you can do today" },
      { p: "Run your key pages through PageSpeed Insights and note your LCP, CLS and INP scores. Install a caching plugin if you're on WordPress (WP Super Cache is free and effective). Run all your images through an online compression tool like Squoosh. Remove any plugins or scripts you don't actively use — one removed plugin can recover more speed than ten optimisation settings. Check whether your hosting plan includes a CDN — edge delivery is one of the fastest single improvements available." },
      { h: "When patching isn't enough: the case for a rebuild" },
      { p: "Some websites can't be made genuinely fast with patches. If your site is built on a heavy page builder, the performance ceiling of that setup is too low to rank competitively against leaner sites. A clean rebuild — a lean framework, hand-coded or headless front-end with a performance budget enforced from the start — often recovers the rebuild cost in six to twelve months through better conversion rates and lower paid acquisition costs needed to compensate for poor organic rankings." },
      { h: "Build it fast from day one" },
      { p: "The cheapest way to have a fast website is to build it fast from the start — clean front-end code, optimised media, and performance budgets baked in — rather than attempting fixes later. If your current site feels sluggish, a focused rebuild often pays for itself in recovered conversions within months. The question to ask any studio you commission: what is your performance budget, and how do you enforce it?" },
      { h: "Benchmarking: how to know if you've improved" },
      { p: "Before making changes, capture your baseline. Run your key pages through PageSpeed Insights three times and average the scores. Also check Core Web Vitals in Google Search Console under the Experience tab — this shows real-world data from actual visitors, which is more meaningful than the lab test. After making changes, wait two to four weeks for sufficient real-world data before judging impact. Track LCP as your primary north-star metric: it has the highest correlation with conversion rate improvements." },
    ],
  },
  {
    slug: "design-systems-101",
    title: "Design Systems 101: Why Your Brand Needs One",
    excerpt:
      "A design system is the difference between a brand that scales and one that's redesigned every year. Here's what a design system is, what it includes, and when your business needs one.",
    date: "2026-04-16",
    read: "5 min",
    tags: ["Design systems", "Brand", "Scale"],
    seoTitle: "Design Systems 101 — Why Your Brand Needs One · Nuvel",
    seoDesc:
      "What a design system is and why your brand needs one — how scalable design systems and component libraries keep your website and product coherent as you grow.",
    body: [
      { p: "If your website, app and marketing all look subtly different, you don't have a branding problem — you have a systems problem. A design system is the shared language that keeps everything coherent as you grow, and it's one of the highest-leverage investments a scaling business can make." },
      { h: "What a design system actually is" },
      { p: "It's more than a logo and a colour palette. A real design system includes type scales, colour tokens, spacing rules, reusable components, and motion guidelines — documented and built so any team can use them. Think of it as the rules of the road for your brand, encoded so they're hard to break." },
      { h: "Why it pays off" },
      { p: "Without a system, every new page or feature is a one-off negotiation. With one, your team ships faster, stays consistent, and stops reinventing buttons. New hires get up to speed quickly, and your brand feels intentional everywhere it shows up — from the website to the product to the pitch deck." },
      { h: "When you need one" },
      { p: "If you're shipping regularly, working with multiple designers or developers, or planning to scale your website or product, you need a design system now. The cost of retrofitting one later — after the inconsistencies have multiplied — is far higher than building it in from the start." },
    ],
  },
  {
    slug: "brief-to-launch-modern-web-design-process",
    title: "From Brief to Launch in Two Weeks: Inside a Modern Web Design Process",
    excerpt:
      "A look behind the curtain at how a modern web design studio takes a project from first call to a live, custom website in two weeks — without the usual agency drag.",
    date: "2026-04-02",
    read: "6 min",
    tags: ["Process", "Web design", "Studio"],
    seoTitle: "From Brief to Launch in Two Weeks — Web Design Process · Nuvel",
    seoDesc:
      "Inside a modern web design process — how a studio takes a brief to a launched, custom website in two weeks with a tight four-step workflow.",
    body: [
      { p: "Clients often ask how a custom website can possibly be designed and built in two weeks. The answer isn't working faster — it's working differently. Here's the four-step process behind a modern web design studio that ships in weeks, not quarters." },
      { h: "1. Spark — align fast" },
      { p: "A focused kickoff pins down the goal, the audience and the single thing the website must achieve. No month-long discovery phase — just enough clarity to design with intent from day one." },
      { h: "2. Shape — real design, early" },
      { p: "Within the first few days you see art direction and key screens — real design, not lorem-ipsum wireframes. Decisions get made while they're still cheap to change." },
      { h: "3. Build — design and code together" },
      { p: "Design and front-end build move in parallel on a shared, tested system. Daily preview links mean you watch your website come together instead of waiting for a big reveal." },
      { h: "4. Launch — and hand over" },
      { p: "We ship a tested, fast, SEO-ready website and hand over a system your team can run. Then we stay on call. The whole arc — brief to launch — fits inside two weeks because the waste has been designed out of it." },
    ],
  },
  {
    slug: "ai-wont-replace-designers",
    title: "AI Won't Replace Designers — But It Will Replace This",
    excerpt:
      "The 'AI will replace designers' panic misses the point. Here's what AI is genuinely automating in web design, what it can't touch, and how the role of the designer is changing.",
    date: "2026-03-19",
    read: "5 min",
    tags: ["AI", "Future of work", "Design"],
    seoTitle: "AI Won't Replace Designers — But It Will Replace This · Nuvel",
    seoDesc:
      "How AI is changing web design — what it automates, what it can't replace, and how designers and design studios are adapting to an AI-assisted workflow.",
    body: [
      { p: "Every few months a new headline declares that AI will replace designers. It won't. But it is replacing a specific slice of the work — and understanding which slice tells you how the design industry is actually changing." },
      { h: "What AI is replacing" },
      { p: "The mechanical middle. Resizing assets, drafting first-pass copy, generating variations, cleaning up images, writing boilerplate code, producing alt-text and translations. This is the work that used to fill a designer's day without using much of their judgement — and it's exactly what AI is good at." },
      { h: "What stays human" },
      { p: "Taste, strategy and accountability. Knowing which idea is worth pursuing, what to cut, how to make a brand feel like itself, and whether a design actually serves the business — none of that is automatable. AI widens the funnel of options; humans still have to choose." },
      { h: "The new shape of the role" },
      { p: "The designers and studios thriving in 2026 treat AI as an accelerant. They ship more, faster, and spend their saved hours on craft and strategy. For clients, that means a web design partner who can move at a speed that used to be impossible — and a better-quality result, not a worse one." },
    ],
  },
  {
    slug: "seo-2026-small-business-websites",
    title: "SEO in 2026: What Actually Moves the Needle for Small Business Websites",
    excerpt:
      "SEO advice is mostly noise. Here's what genuinely helps a small business website rank in 2026 — and the web design decisions that make or break your search visibility.",
    date: "2026-03-05",
    read: "7 min",
    tags: ["SEO", "Small business", "Web design"],
    seoTitle: "SEO in 2026 — What Moves the Needle for Small Business · Nuvel",
    seoDesc:
      "Practical SEO for small business websites in 2026 — the web design, performance and content decisions that actually improve your search rankings.",
    body: [
      { p: "SEO has a noise problem. For every useful idea there are ten gimmicks. For a small business website, the fundamentals haven't changed much — but the weighting has. Here's what actually moves the needle in 2026." },
      { h: "What changed in 2025 and 2026" },
      { p: "Google's helpful content system, which rolled out in stages and was fully integrated into the core algorithm by 2025, has fundamentally changed what ranks. Sites with thin, AI-generated or obviously templated content lost rankings. What gained? Real expertise, genuine experience, and content that helps someone accomplish something specific. For small businesses, this is mostly good news — you have real knowledge that generic content farms don't." },
      { h: "E-E-A-T: why Google's trust signals matter to you" },
      { p: "E-E-A-T stands for Experience, Expertise, Authoritativeness and Trustworthiness. It's Google's framework for evaluating whether a page deserves to rank. For a small business website, this translates to: show who you are, provide real evidence of your expertise (case studies, years in business, credentials, named staff), and be consistent across your online presence. A website that shows the people behind the business, includes genuine testimonials and links to credible sources will outrank an anonymous site with technically similar content." },
      { h: "Speed and Core Web Vitals" },
      { p: "A fast website isn't optional. Page speed and Core Web Vitals are real ranking factors, and they're often the easiest wins for small business sites. Compress images to WebP, ship lean code, lazy-load media below the fold. Most small business sites built on bloated page builders are leaving rankings on the table purely because they're slow." },
      { h: "How to check your Core Web Vitals for free" },
      { p: "Go to PageSpeed Insights and enter your URL. You'll see your Largest Contentful Paint (should be under 2.5 seconds), Cumulative Layout Shift (under 0.1) and Interaction to Next Paint (under 200ms). The most common culprit for small business sites is unoptimised images — a single oversized hero image can fail all three metrics simultaneously. Fixing images alone often moves sites from failing to passing." },
      { h: "Genuinely useful content" },
      { p: "Search engines reward content that answers real questions. A blog with keyword-rich, genuinely helpful articles gives you pages to rank and reasons for people to link to you. Thin, generic content does nothing — and since Google's 2025 updates, it can actively hurt your rankings on other pages too." },
      { h: "How to find keywords your customers actually search" },
      { p: "You don't need expensive tools. Open a private browser window and type your service into Google — the autocomplete suggestions are real searches, not guesses. Scroll to the bottom of search results for 'People also ask' and 'Related searches'. The goal is to find the specific questions your customers ask before hiring someone like you, then answer them thoroughly on your website or blog." },
      { h: "Content length and why your 300-word page doesn't rank" },
      { p: "Google's systems assess whether a page thoroughly covers its topic. A 300-word service page is not thorough — it's a teaser. Pages that rank for competitive queries in 2026 typically run 1,200 words minimum. This doesn't mean padding: it means covering the topic properly — the options, common questions, real examples, costs, timelines. If your service page feels thin, it is, and Google agrees." },
      { h: "Local SEO: the fastest win for most small businesses" },
      { p: "If you serve a specific city or region, local SEO is your biggest short-term lever. Claim and fully optimise your Google Business Profile — it's free and directly affects whether you appear in map results. Ensure your business name, address and phone number are identical everywhere online. Get Google reviews — they're a real ranking factor and the first thing potential customers check. A local business with 20 genuine reviews will outrank a bigger competitor with none." },
      { h: "Technical hygiene" },
      { p: "Clean markup, one clear H1 per page, descriptive titles and meta descriptions under 160 characters, alt-text on all images, a sitemap, HTTPS, and structured data (Schema.org). None of it is glamorous, but it's the foundation everything else sits on — and it's exactly what a good web design studio should bake in by default, not charge extra for." },
      { h: "Internal linking: the underused tactic" },
      { p: "Internal links — from one page on your site to another — help Google understand which pages are important and how they relate. A common mistake: blog posts don't link to service pages, and service pages don't link to case studies. Add a related services section to blog posts. Link service pages to relevant case studies. Every new piece of content should link to at least two other pages on your site. It's free, takes minutes, and most small business sites never do it." },
      { h: "How to get backlinks without a big budget" },
      { p: "Backlinks — other sites linking to yours — remain one of Google's strongest signals. For small businesses: get listed on industry-specific directories (free, takes an hour), contribute to local business blogs or industry publications, and ask happy clients to link to your site in their own content. One good link from a relevant, trusted site is worth more than a hundred spammy directory submissions." },
      { h: "The web design connection" },
      { p: "SEO isn't a separate task you bolt on after launch — it's a product of how the site is designed and built. Performance, semantic structure, Schema.org markup, and content architecture are design decisions made at the start of a project, not afterthoughts. Choose a studio that treats these as first-class concerns, and you'll rank without fighting your own website." },
      { h: "What to measure and how often" },
      { p: "Set up Google Search Console if you haven't already — it shows exactly which queries bring people to your site, which pages are indexed, and which have errors. Check it monthly. Also set up Google Analytics 4 and track which pages drive the most enquiries or sales, not just the most traffic. The goal isn't rankings for their own sake: it's rankings for queries that bring customers who actually buy." },
    ],
  },
  {
    slug: "ecommerce-ux-fixes-that-lift-conversion",
    title: "E-commerce UX: 7 Fixes That Lift Conversion",
    excerpt:
      "Small UX changes can move e-commerce conversion more than a redesign. Here are seven high-impact fixes — from product pages to checkout — that turn browsers into buyers.",
    date: "2026-02-19",
    read: "6 min",
    tags: ["E-commerce", "UX", "Conversion"],
    seoTitle: "E-commerce UX — 7 Fixes That Lift Conversion · Nuvel",
    seoDesc:
      "Seven high-impact e-commerce UX fixes that lift conversion — practical web design improvements for product pages, navigation and checkout.",
    body: [
      { p: "You don't always need a full redesign to sell more. Most e-commerce websites are losing sales to friction that's cheap to fix. Here are ten UX changes that reliably lift conversion — with the research behind them." },
      { h: "1. Make the primary action obvious" },
      { p: "One clear, high-contrast 'add to cart' or 'buy' button per screen. If everything shouts, nothing converts. The button should be visible without scrolling on mobile, use your brand's strongest accent colour, and carry unambiguous text — 'Add to Bag' beats 'Proceed'. Every competing element you remove from that screen is a micro-conversion gain." },
      { h: "2. Speed up product pages" },
      { p: "Compress product imagery to WebP and lazy-load below-the-fold images. A fast product page is one of the strongest single conversion levers in e-commerce — Portent's research shows conversion rates roughly halve between a one-second and a five-second load time. Serve product images from a CDN and defer any non-essential scripts on product pages specifically, since that's where the sale is won or lost." },
      { h: "3. Show price and shipping early" },
      { p: "Surprise costs at checkout are the number-one cause of cart abandonment — consistently ranked first in Baymard Institute's research across thousands of checkout studies. Show your shipping cost (or 'free shipping on orders over X') on the product page itself, not only at checkout. If you can't offer free shipping, displaying the cost early means it's already mentally processed before the customer reaches the payment screen." },
      { h: "4. Reduce checkout steps" },
      { p: "Every field and step is a chance to lose the sale. Baymard's research found that 28% of shoppers have abandoned a checkout purely because the site required account creation before purchase. Guest checkout is table stakes. Aim for five fields or fewer: name, email, address, and payment. Autofill support, a single-page checkout, and address lookup APIs all reduce friction measurably. Every field you add costs you a percentage of completions." },
      { h: "5. Build trust on the page" },
      { p: "Reviews, a clear returns policy, and secure-payment cues do quiet, constant work. A product page with 20 verified reviews converts significantly better than the same page with none — even mediocre reviews outperform no reviews. Show your returns policy on the product page, not buried in a footer. Display payment provider logos (Visa, Mastercard, PayPal, Apple Pay) near the buy button — the visual familiarity reduces payment anxiety at the exact moment of decision." },
      { h: "6. Design mobile-first" },
      { p: "More than 60% of e-commerce traffic is now mobile, yet mobile converts at roughly half the rate of desktop — and the gap is almost entirely UX friction. Tap targets need to be at least 44px tall. The checkout form should use the right keyboard type for each field (numeric for card numbers, email keyboard for email fields). The cart should be accessible without leaving the product page. Test your full checkout on a real phone before you consider it done." },
      { h: "7. Make search and filtering work" },
      { p: "If people can't find it, they can't buy it. Baymard's research shows that shoppers who use site search convert at two to three times the rate of browsers — making search one of the highest-leverage features to invest in. Your search should handle misspellings and synonyms. Filters should update the page without a full reload. On mobile, filters should expand into a usable full-screen drawer. These aren't nice-to-haves; they're where a large share of high-intent buyers decide whether to stay or leave." },
      { h: "8. Reduce friction for returning customers" },
      { p: "Returning customers convert at two to four times the rate of new visitors — yet most e-commerce sites treat them identically to strangers. Logged-in customers should see their saved addresses and payment methods auto-populated. A 'buy again' shortcut in order history removes an entire decision journey for repeat purchases. If your platform supports it, smart re-order suggestions based on past purchases can meaningfully lift revenue per returning session." },
      { h: "9. Use urgency and scarcity honestly" },
      { p: "Low-stock indicators ('Only 3 left') and time-limited offers drive conversions when they're true. Dark patterns — fake scarcity, always-on 'sale' prices, fake countdown timers — erode trust over time and invite regulatory scrutiny in an increasing number of markets. Real urgency (a genuine last batch, a real shipping cutoff for a holiday) can lift conversion significantly on the affected products. Your customers are more sceptical than most e-commerce sites assume." },
      { h: "10. Optimise category pages, not just product pages" },
      { p: "Most conversion work focuses on product pages, but category pages are where shoppers decide whether to browse deeper or bounce. A strong category page has featured products at the top, filters visible without scrolling on mobile, consistent image sizing, and a brief keyword-rich description — which also helps SEO. If your category pages are just an unsorted grid with no context, you're losing a significant share of visitors before they even see the products you want them to buy." },
      { h: "Measuring the impact: the right metrics" },
      { p: "Add-to-cart rate and checkout completion rate are more actionable than overall conversion rate — they tell you exactly where in the funnel you're losing people. Use session recordings (Hotjar or Microsoft Clarity, both free) to watch real users navigate your store. The patterns you see — where they pause, scroll back, or abandon — are worth more than any survey. Run one change at a time, give it two to four weeks, and measure before and after. Gut instinct is a good starting point; data is how you confirm it." },
    ],
  },
  {
    slug: "wordpress-headless-or-custom-how-to-choose",
    title: "WordPress, Headless or Custom? How to Choose the Right Build for Your Website",
    excerpt:
      "The way your website is built shapes its speed, cost and future. Here's a clear-headed comparison of WordPress, headless and custom-coded approaches — and how to pick the right one.",
    date: "2026-02-05",
    read: "6 min",
    tags: ["Web development", "Tech", "Strategy"],
    seoTitle: "WordPress, Headless or Custom? How to Choose Your Build · Nuvel",
    seoDesc:
      "WordPress vs headless vs custom-coded websites — a practical comparison of web development approaches for speed, flexibility and long-term cost.",
    body: [
      { p: "How your website is built matters as much as how it looks. The three most common build paths — WordPress, headless and fully custom — each suit different goals, teams and budgets. Here's how to choose without the hype." },
      { h: "WordPress" },
      { p: "Still powers about 40% of the web for a reason. A mature plugin ecosystem, familiar admin, and a huge talent pool make it easy to maintain. The catch: performance requires careful tuning, and the plugin stack can become a liability. Best for content-heavy sites where the team is comfortable inside the CMS." },
      { h: "Headless" },
      { p: "A modern front-end — usually React or Next.js — talking to a separate content backend like Sanity or Contentful. You get near-perfect performance scores, complete design freedom and content that's truly portable. More to set up, but it scales cleanly and puts developers in full control of every interaction." },
      { h: "Fully custom" },
      { p: "Maximum control and performance with zero platform overhead. Right for bespoke experiences, complex interactions or products that don't fit a template. Needs a capable team and a clear brief — but the result is lean, fast and built exactly to spec." },
      { h: "How to choose" },
      { p: "Match the build to who will maintain it and where you're headed in 18 months. A good web design and development studio will recommend the approach that fits your goals — not the one that's easiest for them. If a studio only ever builds one way, that's a red flag." },
    ],
  },
  {
    slug: "anatomy-of-a-high-converting-landing-page",
    title: "The Anatomy of a High-Converting Landing Page",
    excerpt:
      "A landing page has one job: convert. Here's the anatomy of a high-converting page — section by section — and the web design choices that turn traffic into action.",
    date: "2026-01-22",
    read: "6 min",
    tags: ["Landing pages", "Conversion", "Web design"],
    seoTitle: "The Anatomy of a High-Converting Landing Page · Nuvel",
    seoDesc:
      "The anatomy of a high-converting landing page — section by section web design and copy choices that turn campaign traffic into leads and sales.",
    body: [
      { p: "A landing page isn't a mini-website — it's a single-minded conversion machine. Every section either moves the visitor toward one action or it's getting in the way. Here's the anatomy that works." },
      { h: "A headline that makes a promise" },
      { p: "The first thing people read should state the value clearly and specifically. Clever comes second to clear. If a visitor can't tell what you offer in three seconds, the rest of the page never gets read." },
      { h: "One primary call to action" },
      { p: "Pick one action and design the whole page around it. Repeat the CTA as the page gets long, but never compete with it. A landing page with five different asks converts on none of them." },
      { h: "Proof and objection-handling" },
      { p: "Social proof, results, and answers to the obvious 'but what about…' questions. Trust is built in the gaps between the headline and the button." },
      { h: "Speed and focus" },
      { p: "A high-converting landing page loads fast and removes distractions — no full navigation, no rabbit holes. The web design exists to protect the single path to conversion. Get that right and the same traffic suddenly performs." },
    ],
  },
];
